# -*- coding: utf-8 -*-
"""Student Exam Score Analyses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BMg9v9ZdnpvnhLhWr3FYq8-uYwpFr-Tb

Here are some questions you can answer using the Students Exam Scores dataset and Pandas:

1. What is the average score for each test?
    
2. What is the distribution of scores for each test?
    
3. What are the correlations between the different variables?
    
4. Is there a difference in scores between boys and girls?
    
5. Is there a difference in scores between students of different ethnic groups?
    
6. Is there a difference in scores between students with different levels of parental education?
    
7. Is there a difference in scores between students who eat standard or free/reduced lunch?
    
8. Did students who completed a test preparation course score higher?
    
9. Is there a difference in scores between students with different marital statuses of their parents?
    
10. Do students who practice sports more often score higher?
    
11. Are first-born children more likely to score higher than later-born children?
    
12. Is there a difference in scores between students with different numbers of siblings?
"""

import pandas as pd
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

df = pd.read_csv("Expanded_data_with_more_features.csv", index_col=False)

df.head()

"""### Student Gender Statistics"""

df['Gender'].value_counts()

femaleStudents = df['Gender'].value_counts()['female']
maleStudents = df['Gender'].value_counts()['male']

plt.bar(['Female', 'Male'], [femaleStudents, maleStudents], color=['blue', 'red'])

plt.xlabel('Gender')
plt.ylabel('Number of Students')
plt.title('Number of Female and Male Students')

maleStudents/femaleStudents

"""### Average Test Score"""

df.head(5)

df['total_score'] = df['MathScore']+df['ReadingScore']+df['WritingScore']

gp = df.groupby("Gender")

gp.mean()

"""### Does sports help in good grades?

Ans: No, sports does not imapact the scores of the students as per the data in this data set. Note, actual scenario may be different.
"""



def sports_sort(x):
    if x == "sometimes":
        return 1
    elif x == "regularly":
        return 0.5
    else:
        return 0

df["sports_practice"] = df["PracticeSport"].apply(sports_sort)

df[["sports_practice", "total_score"]].corr()

"""### Ethnic Groups"""

eg = df.groupby("EthnicGroup")

eg.mean()

"""### Are first-born children more likely to score higher than later-born children?"""

df.head()

def is_firstchild(x):
  return x=="yes"

df['IsFirstChild_Bool'] = df['IsFirstChild'].apply(is_firstchild)

df_firstchildgrp = df.groupby("IsFirstChild_Bool")

df_firstchildgrp.mean()

"""### Does parents qualification impact students score?"""

df_parentedugrp = df.groupby("ParentEduc")

df_parentedugrp.mean()